version: '3.3'
volumes:
  food_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - food_data:/var/lib/postgresql/data
  backend:
    image: denchur/food_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: denchur/food_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: denchur/food_nginx
    volumes:
      - static:/staticfiles/
      - media:/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
     - 8000:80

