version: '3.3'
volumes:
  food_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - food_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    build: ../infra/
    volumes:
      - static:/staticfiles/
      - media:/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
     - 8000:80
